name = "PMParameterizedBase"
uuid = "e616dab5-0079-4c8e-a420-383be346beea"
authors = ["Timothy Knab"]
version = "1.0.0-DEV"

[compat]
julia = "1.9.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
